### ISSUE TITLE
你好 我想这个项目用什么编辑器打开呢？我想运行下看看

### ISSUE THREAD

**Issue by hjx503838528** [zspark/lsx#1]

**Comment by zspark** [comment]
你好，我回去写一下怎么用，chrome浏览器必备。发自我的手机-------- 原始邮件 --------主题：[zspark/lsx] 你好 我想这个项目用什么编辑器打开呢？我想运行下看看 (#1)发件人：hjx503838528 收件人：zspark/lsx 抄送：Subscribed

**Comment by hjx503838528** [comment]
麻烦了  我想拿来学习下  现在都打不开运行部了

**Comment by zspark** [comment]
OK，我的荣幸，互相学习，回家我整理下。发自我的手机-------- 原始邮件 --------主题：Re: [zspark/lsx] 你好 我想这个项目用什么编辑器打开呢？我想运行下看看 (#1)发件人：hjx503838528 收件人：zspark/lsx 抄送：Jerry Chaos ,Comment 麻烦了  我想拿来学习下  现在都打不开运行部了

**Comment by zspark** [comment]
使用chrome浏览器，然后下载hfs（一个简单的http服务器），解压version/v2_0/中的7z压缩包，用http服务器运行里面的html文件即可（记得让chrome浏览器支持flash播放器，chrome现在默认不开启flash播放器的支持），如有任何问题咱们可进一步交流。

**Comment by zspark** [comment]
这是运行结果：
![image](https://user-images.githubusercontent.com/6628743/67398928-04961400-f5de-11e9-8e5e-05871bc9c2dc.png)

**Comment by hjx503838528** [comment]
收到 谢谢

**Comment by hjx503838528** [comment]
我想研究下斜掉落的算法   你这个我有点看不懂  你能说下大概逻辑吗

**Comment by zspark** [comment]
我实在不记得了，2013年的程序了，再过些时间浏览器都不支持了。13年底左右我移植到js版本，不过找不到源码了。
